#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
upgrade_project.py
Doplní do existujícího 'cnc-capture' projektu Alembic migrace + seed, Admin UI (frontend),
Playwright E2E tests a CI/CD workflow.
Spusť ve stejném adresáři, kde je složka 'cnc-capture'.
"""
import os
import shutil
from pathlib import Path
from textwrap import dedent
import zipfile

ROOT = Path.cwd() / "cnc-capture"
if not ROOT.exists():
    raise SystemExit("Adresář 'cnc-capture' nebyl nalezen. Ujisti se, že jsi spustil build_project.py nebo máš projekt ve složce 'cnc-capture'.")

ADDITIONS = {
    # Alembic ini (root for backend)
    "backend/alembic.ini": dedent("""\
        [alembic]
        script_location = backend/app/alembic
        sqlalchemy.url = %(DATABASE_URL)s

        [loggers]
        keys = root,sqlalchemy,alembic

        [handlers]
        keys = console

        [formatters]
        keys = generic

        [logger_root]
        level = WARN
        handlers = console
        qualname =

        [handler_console]
        class = StreamHandler
        args = (sys.stderr,)
        formatter = generic

        [formatter_generic]
        format = %(levelname)-5.5s [%(name)s] %(message)s
        """),

    # Alembic migration (creates tables)
    "backend/app/alembic/versions/0001_create_tables.py": dedent("""\
        \"\"\"create initial tables

        Revision ID: 0001_create_tables
        Revises: 
        Create Date: autogenerated
        \"\"\"
        from alembic import op
        import sqlalchemy as sa

        # revision identifiers, used by Alembic.
        revision = '0001_create_tables'
        down_revision = None
        branch_labels = None
        depends_on = None

        def upgrade():
            op.create_table('users',
                sa.Column('id', sa.Integer(), primary_key=True),
                sa.Column('username', sa.String(), nullable=False, unique=True),
                sa.Column('full_name', sa.String(), nullable=True),
                sa.Column('email', sa.String(), nullable=True),
            )
            op.create_table('machines',
                sa.Column('id', sa.Integer(), primary_key=True),
                sa.Column('name', sa.String(), nullable=False),
            )
            op.create_table('jobs',
                sa.Column('id', sa.Integer(), primary_key=True),
                sa.Column('name', sa.String(), nullable=True),
                sa.Column('customer', sa.String(), nullable=True),
            )
            op.create_table('drawings',
                sa.Column('id', sa.Integer(), primary_key=True),
                sa.Column('job_id', sa.Integer(), sa.ForeignKey('jobs.id')),
                sa.Column('drawing_number', sa.String(), nullable=True),
                sa.Column('planned_time_per_piece', sa.Integer(), nullable=True),
                sa.Column('planned_pieces', sa.Integer(), nullable=True),
            )
            op.create_table('job_cards',
                sa.Column('id', sa.Integer(), primary_key=True),
                sa.Column('drawing_id', sa.Integer(), sa.ForeignKey('drawings.id')),
                sa.Column('card_number', sa.String(), nullable=True),
                sa.Column('qr_payload', sa.String(), nullable=True),
            )
            op.create_table('sessions',
                sa.Column('id', sa.Integer(), primary_key=True),
                sa.Column('job_card_id', sa.Integer(), sa.ForeignKey('job_cards.id')),
                sa.Column('operator_id', sa.Integer(), sa.ForeignKey('users.id')),
                sa.Column('machine_id', sa.Integer(), sa.ForeignKey('machines.id')),
                sa.Column('piece_index', sa.Integer(), nullable=True),
                sa.Column('start_ts', sa.DateTime(timezone=True), nullable=True),
                sa.Column('stop_ts', sa.DateTime(timezone=True), nullable=True),
                sa.Column('duration_seconds', sa.Integer(), nullable=True),
                sa.Column('status', sa.String(), nullable=True),
                sa.Column('meta', sa.JSON(), nullable=True),
            )

        def downgrade():
            op.drop_table('sessions')
            op.drop_table('job_cards')
            op.drop_table('drawings')
            op.drop_table('jobs')
            op.drop_table('machines')
            op.drop_table('users')
        """),

    # seed script (simple)
    "backend/scripts/seed.py": dedent("""\
        #!/usr/bin/env python3
        \"\"\"Seed script — vloží jednoduché demo uživatele, stroje a ukázkovou zakázku.\"\"\"
        import asyncio
        from app.db.session import AsyncSessionLocal, engine
        from app.db.base import Base
        from app.db.models import User, Machine, Job, Drawing, JobCard
        from app.services.qr import build_qr_payload

        async def run():
            async with engine.begin() as conn:
                # create tables if not exist
                await conn.run_sync(Base.metadata.create_all)
            async with AsyncSessionLocal() as s:
                # create demo user
                u = User(username='operator1', full_name='Operátor 1', email='op1@example.com')
                s.add(u)
                m = Machine(name='MAZAK-1')
                s.add(m)
                job = Job(name='Demo zakázka', customer='Acme')
                s.add(job)
                await s.flush()
                drawing = Drawing(job_id=job.id, drawing_number='D-100', planned_time_per_piece=60, planned_pieces=3)
                s.add(drawing)
                await s.flush()
                jc = JobCard(drawing_id=drawing.id, card_number='JC-100')
                s.add(jc)
                await s.flush()
                # build QR payload
                jc.qr_payload = build_qr_payload(jc.id)
                await s.commit()
                print('Seed data created: user id', u.id, 'machine id', m.id, 'jobcard id', jc.id)

        if __name__ == '__main__':
            asyncio.run(run())
        """),

    # JWT helper for backend
    "backend/app/core/jwt.py": dedent("""\
        from datetime import datetime, timedelta
        from jose import jwt
        from app.core.config import settings

        def create_access_token(subject: str, expires_delta: timedelta = None):
            if expires_delta is None:
                expires_delta = timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
            expire = datetime.utcnow() + expires_delta
            to_encode = {"sub": subject, "exp": expire.isoformat()}
            encoded = jwt.encode(to_encode, settings.SECRET_KEY, algorithm="HS256")
            return encoded
        """),

    # Frontend admin + auth: new pages
    "frontend/src/pages/Login.jsx": dedent("""\
        import React, {useState} from 'react';

        export default function Login({onLogin}) {
          const [username, setUsername] = useState('');
          const [loading, setLoading] = useState(false);
          const submit = async (e) => {
            e.preventDefault();
            setLoading(true);
            const res = await fetch('/api/v1/auth/login', {
              method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({username})
            });
            const data = await res.json();
            setLoading(false);
            if (data.access_token) {
              localStorage.setItem('token', data.access_token);
              onLogin();
            }
          };
          return (
            <form onSubmit={submit}>
              <h3>Login</h3>
              <input value={username} onChange={e=>setUsername(e.target.value)} placeholder="username" />
              <button type="submit" disabled={loading}>Login</button>
            </form>
          );
        }
        """),

    "frontend/src/pages/Admin.jsx": dedent("""\
        import React, {useEffect, useState} from 'react';

        function fetchAuth(path, opts={}) {
          const token = localStorage.getItem('token');
          opts.headers = {...(opts.headers||{}), Authorization: `Bearer ${token}`, 'Content-Type':'application/json'};
          return fetch(path, opts).then(r=>r.json());
        }

        export default function Admin(){
          const [jobs, setJobs] = useState([]);
          const [machines, setMachines] = useState([]);
          const [users, setUsers] = useState([]);
          const [name, setName] = useState('');
          useEffect(()=>{ load(); },[]);
          async function load(){
            const j = await fetchAuth('/api/v1/jobs/list').catch(()=>[]);
            const m = await fetchAuth('/api/v1/machines/list').catch(()=>[]);
            setJobs(j || []);
            setMachines(m || []);
          }
          async function createJob(){
            const res = await fetchAuth('/api/v1/jobs', {method:'POST', body: JSON.stringify({name, customer:''})});
            setName('');
            load();
          }
          return (
            <div>
              <h2>Admin</h2>
              <div>
                <h4>Jobs</h4>
                <input value={name} onChange={e=>setName(e.target.value)} placeholder="Job name" />
                <button onClick={createJob}>Create</button>
                <ul>{jobs.map(j=> <li key={j.id}>{j.name} (id:{j.id})</li>)}</ul>
              </div>
            </div>
          );
        }
        """),

    "frontend/src/pages/Scanner.jsx": dedent("""\
        import React, { useEffect, useRef, useState } from \"react\";
        import { BrowserMultiFormatReader } from \"@zxing/browser\";

        export default function Scanner() {
          const videoRef = useRef();
          const [result, setResult] = useState(null);
          const [operatorId, setOperatorId] = useState(1);
          const [machineId, setMachineId] = useState(1);

          useEffect(() => {
            const codeReader = new BrowserMultiFormatReader();
            let selectedDeviceId;

            codeReader
              .listVideoInputDevices()
              .then(videoInputDevices => {
                if (videoInputDevices.length > 0) {
                  selectedDeviceId = videoInputDevices[0].deviceId;
                  codeReader.decodeFromVideoDevice(selectedDeviceId, videoRef.current, (result, err) => {
                    if (result) {
                      setResult(result.getText());
                      const token = localStorage.getItem('token');
                      fetch('/api/v1/scan', {
                        method: 'POST',
                        headers: {'Content-Type':'application/json', Authorization: `Bearer ${token}`},
                        body: JSON.stringify({ operator_id: operatorId, machine_id: machineId, qr_payload: result.getText() })
                      }).then(r=>r.json()).then(console.log).catch(console.error);
                    }
                  });
                }
              })
              .catch(err => console.error(err));

            return () => {
              codeReader.reset();
            };
          }, [operatorId, machineId]);

          return (
            <div>
              <h3>Scanner</h3>
              <div>
                Operator id: <input type="number" value={operatorId} onChange={e=>setOperatorId(+e.target.value)} />
                Machine id: <input type="number" value={machineId} onChange={e=>setMachineId(+e.target.value)} />
              </div>
              <video ref={videoRef} style={{width: \"100%\", maxWidth: 640}} />
              <div>Last QR: {result}</div>
            </div>
          );
        }
        """),

    # update main.jsx to provide basic routing
    "frontend/src/main.jsx": dedent("""\
        import React from 'react'
        import { createRoot } from 'react-dom/client'
        import App from './App'
        import './style.css'

        createRoot(document.getElementById('root')).render(<App />)
        """),

    "frontend/src/App.jsx": dedent("""\
        import React, {useState} from 'react';
        import Login from './pages/Login';
        import Admin from './pages/Admin';
        import Scanner from './pages/Scanner';

        export default function App(){
          const [authed, setAuthed] = useState(!!localStorage.getItem('token'));
          if (!authed) return <Login onLogin={()=>setAuthed(true)} />
          return (
            <div style={{padding:20}}>
              <h1>CNC Capture — Admin / Scanner</h1>
              <div style={{display:'flex',gap:20}}>
                <div style={{flex:1}}><Admin /></div>
                <div style={{flex:1}}><Scanner /></div>
              </div>
            </div>
          );
        }
        """),

    # backend small endpoints for lists used by Admin UI
    "backend/app/api/v1/admin_endpoints.py": dedent("""\
        from fastapi import APIRouter, Depends
        from app.db.session import AsyncSessionLocal
        from app.db.models import Job, Machine, User
        from sqlalchemy import select

        router = APIRouter()

        async def get_db():
            async with AsyncSessionLocal() as s:
                yield s

        @router.get('/jobs/list')
        async def list_jobs(db=Depends(get_db)):
            r = await db.execute(select(Job))
            rows = r.scalars().all()
            return [{"id":row.id,"name":row.name} for row in rows]

        @router.get('/machines/list')
        async def list_machines(db=Depends(get_db)):
            r = await db.execute(select(Machine))
            rows = r.scalars().all()
            return [{"id":row.id,"name":row.name} for row in rows]
        """),

    # E2E Playwright config + test (typescript)
    "e2e/playwright.config.ts": dedent("""\
        import { defineConfig } from '@playwright/test';

        export default defineConfig({
          testDir: './tests',
          timeout: 30_000,
          expect: { timeout: 5000 },
          use: {
            baseURL: 'http://localhost:5173',
            headless: true,
          },
        });
        """),

    "e2e/tests/e2e.spec.ts": dedent("""\
        import { test, expect } from '@playwright/test';

        test('login and create job via admin UI', async ({ page }) => {
          await page.goto('/');
          // login (there is no real password)
          await page.fill('input[placeholder=\"username\"]', 'e2e-user');
          await page.click('button:has-text(\"Login\")');
          // wait for admin to load
          await page.waitForSelector('h2:has-text(\"Admin\")');
          // create job
          await page.fill('input[placeholder=\"Job name\"]', 'E2E Job');
          await page.click('button:has-text(\"Create\")');
          // expect item visible
          await expect(page.locator('li')).toContainText('E2E Job');
        });
        """),

    # Playwright package.json
    "e2e/package.json": dedent("""\
        {
          "name": "cnc-e2e",
          "devDependencies": {
            "@playwright/test": "^1.40.0"
          },
          "scripts": {
            "test": "playwright test"
          }
        }
        """),

    # CI/CD github workflow (build & push)
    ".github/workflows/ci_cd.yml": dedent("""\
        name: CI/CD

        on:
          push:
            branches: [ main ]
          pull_request:
            branches: [ main ]

        jobs:
          test:
            runs-on: ubuntu-latest
            services:
              postgres:
                image: postgres:15
                env:
                  POSTGRES_USER: cnc
                  POSTGRES_PASSWORD: cncpass
                  POSTGRES_DB: cnc
                ports:
                  - 5432:5432
              redis:
                image: redis:7
                ports:
                  - 6379:6379
            steps:
              - uses: actions/checkout@v4
              - name: Set up Python
                uses: actions/setup-python@v4
                with:
                  python-version: 3.11
              - name: Install backend deps
                run: |
                  pip install -r backend/requirements.txt
              - name: Run pytest
                run: |
                  pytest -q

          build_push:
            needs: test
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
              - name: Log in to DockerHub
                uses: docker/login-action@v2
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
              - name: Build and push
                uses: docker/build-push-action@v4
                with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/cnc-capture:latest
        """),
}

def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')
    print(f"wrote {path}")

def main():
    print("Applying upgrade: adding Alembic migrations, seed, frontend admin, E2E tests, CI/CD...")
    for rel, content in ADDITIONS.items():
        target = ROOT / rel
        write(target, content)
    # ensure executable for seed
    seed_path = ROOT / "backend" / "scripts" / "seed.py"
    if seed_path.exists():
        seed_path.chmod(0o755)
    # create zip of updated project
    zip_path = Path.cwd() / "cnc-capture-upgraded.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for folder, subs, files in os.walk(ROOT):
            for f in files:
                full = os.path.join(folder, f)
                z.write(full, os.path.relpath(full, ROOT.parent))
    print(f"Upgrade complete. Archive: {zip_path}")
    print("Next steps:")
    print("  - Edit cnc-capture/.env (QR_SECRET, SECRET_KEY, DB connection etc.)")
    print("  - Run migrations: cd cnc-capture/backend && alembic -c alembic.ini upgrade head")
    print("  - Run seed: python backend/scripts/seed.py")
    print("  - Run docker compose: docker compose up --build")
    print("  - For E2E: install playwright (e2e dir) and run tests when frontend is available.")

if __name__ == '__main__':
    main()
