"""create initial tables

Revision ID: 0001_create_tables
Revises: 
Create Date: autogenerated
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_create_tables'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('users',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('username', sa.String(), nullable=False, unique=True),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
    )
    op.create_table('machines',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(), nullable=False),
    )
    op.create_table('jobs',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('customer', sa.String(), nullable=True),
    )
    op.create_table('drawings',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('job_id', sa.Integer(), sa.ForeignKey('jobs.id')),
        sa.Column('drawing_number', sa.String(), nullable=True),
        sa.Column('planned_time_per_piece', sa.Integer(), nullable=True),
        sa.Column('planned_pieces', sa.Integer(), nullable=True),
    )
    op.create_table('job_cards',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('drawing_id', sa.Integer(), sa.ForeignKey('drawings.id')),
        sa.Column('card_number', sa.String(), nullable=True),
        sa.Column('qr_payload', sa.String(), nullable=True),
    )
    op.create_table('sessions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('job_card_id', sa.Integer(), sa.ForeignKey('job_cards.id')),
        sa.Column('operator_id', sa.Integer(), sa.ForeignKey('users.id')),
        sa.Column('machine_id', sa.Integer(), sa.ForeignKey('machines.id')),
        sa.Column('piece_index', sa.Integer(), nullable=True),
        sa.Column('start_ts', sa.DateTime(timezone=True), nullable=True),
        sa.Column('stop_ts', sa.DateTime(timezone=True), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
    )

def downgrade():
    op.drop_table('sessions')
    op.drop_table('job_cards')
    op.drop_table('drawings')
    op.drop_table('jobs')
    op.drop_table('machines')
    op.drop_table('users')
